language: csharp
dist: trusty
mono: none
dotnet: 2.0.0

install:
- dotnet restore modifi/Connectors
- dotnet restore modifi/Storage
- dotnet restore modifi/Core

script:
- dotnet build modifi/Core
- dotnet test test/Modifi