language: csharp
dist: trusty
mono: none
dotnet: 2.0.0

script:
  - dotnet build modifi/Launcher
  - dotnet test test/Modifi

before_deploy:
  - dotnet publish -c Release

deploy:
  provider: releases
  api_key: $RELEASES_API_KEY
  file_glob: true
  file: publish/*
  skip_cleanup: true
  on:
    tags: true